sudo: false
language: node_js
node_js:
  - '5'
env:
  - CXX=g++-4.8

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

after_success:
  - tools/docker-build.sh
